<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0.3 (Python 3.9.5 on win32)" generated="20210705 03:54:39.639" rpa="false" schemaversion="2">
<suite id="s1" name="Mobile Testing" source="C:\Users\vaaxa\OneDrive\Backup Dropbox\Backup Onedrvive\Documentos\Projetos\Prime Experts\PrimeExperts_junho_28_2021\mobile_testing">
<suite id="s1-s1" name="Mobile Test" source="C:\Users\vaaxa\OneDrive\Backup Dropbox\Backup Onedrvive\Documentos\Projetos\Prime Experts\PrimeExperts_junho_28_2021\mobile_testing\mobile_test.robot">
<kw name="Abrir o aplicativo no celular" library="resource.mobile" type="SETUP">
<kw name="Open Application" library="AppiumLibrary">
<arg>${REMOTE_URL}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>platformVersion=${PLATFORM_VERSION}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>appPackage=${APP_PACKAGE}</arg>
<arg>appActivity=${APP_ACTIVITY}</arg>
<arg>automationName=${AUTOMATION_NAME}</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<msg timestamp="20210705 03:54:41.960" level="INFO">Could not connect to port 4723 on host localhost</msg>
<msg timestamp="20210705 03:54:41.960" level="INFO">Could not get IP address for host: localhost</msg>
<msg timestamp="20210705 03:54:46.073" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002A5C41490D0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20210705 03:54:50.147" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002A5C4149310&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20210705 03:54:54.232" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002A5C4149490&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210705 03:54:58.340" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210705 03:54:58.310" endtime="20210705 03:54:58.340"/>
</kw>
<msg timestamp="20210705 03:54:58.340" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210705 03:54:58.361" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002A5C41495E0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<status status="FAIL" starttime="20210705 03:54:39.930" endtime="20210705 03:54:58.361"/>
</kw>
<status status="FAIL" starttime="20210705 03:54:39.929" endtime="20210705 03:54:58.361"/>
</kw>
<test id="s1-s1-t1" name="Pesquisar canal “Adrenaline”">
<status status="FAIL" starttime="20210705 03:54:58.361" endtime="20210705 03:54:58.367">Parent suite setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002A5C41495E0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</test>
<doc>arquivo responsavel pelos testes do mobile testing App: YouTube</doc>
<status status="FAIL" starttime="20210705 03:54:39.675" endtime="20210705 03:54:58.372">Suite setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002A5C41495E0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</suite>
<status status="FAIL" starttime="20210705 03:54:39.642" endtime="20210705 03:54:58.379"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Mobile Testing">Mobile Testing</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Mobile Test">Mobile Testing.Mobile Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210705 03:54:46.073" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002A5C41490D0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20210705 03:54:50.147" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002A5C4149310&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20210705 03:54:54.232" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002A5C4149490&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20210705 03:54:58.340" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
